Boas praticas para imagens docker
lichti/containers4docker pull request #5
Opened 2017-06-22 22:40 UTC by farribeiro

Boas praticas para imagens docker.

Muitos autores recomenda não utilizar em imagem para o HUB uso excessivo de etapas.

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

2017-06-22 22:45 UTC, farribeiro commented
Gentileza, descartar PR. Irei basear no branch master

2017-06-23 13:53 UTC, diraol requested changes

2017-06-23 13:53 UTC, diraol commented on warsaw-browser/Dockerfile
> +  && useradd -u 1000 -r -g bank -G audio,video bank \
Acho que dá para juntar as duas linhas abaixo nesta linha com:
``&& useradd -u 1000 -r -g bank -G audio,video bank -d /home/bank \``

2017-06-23 13:56 UTC, diraol commented on warsaw-browser/Dockerfile
>    && apt install -qqy \
eu adicionaria também, no `apt install`, o parâmetro `--no-install-recommends`

2017-06-23 19:24 UTC, farribeiro commented on warsaw-browser/Dockerfile
>    && apt install -qqy \
Irei fazer mais um commit para este PR com o --no-install-recommends

2017-06-23 19:24 UTC, farribeiro commented on warsaw-browser/Dockerfile
> +  && useradd -u 1000 -r -g bank -G audio,video bank \
A intenção não era alterar e simplificar os comandos, e sim a quantidade de etapas RUN porém é bem vindo a seu apontamento..

2017-07-01 12:51 UTC, farribeiro commented on warsaw-browser/Dockerfile
>    && apt install -qqy \
Feito

2017-07-01 12:53 UTC, farribeiro reviewed
Feito

2017-08-01 00:55 UTC, lichti approved these changes

2017-08-01 00:55 UTC, merged